### ISSUE TITLE
ConductivityGenFigs.ipynb Failing

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em_examples#16]
The notebook: /em_examples/notebooks/physical_properties/ConductivityGenFigs.ipynb is failing. 

See [travis log](https://travis-ci.org/ubcgif/em_examples/builds/160711023) starting at line 361 (partially copied below) 
![image](https://cloud.githubusercontent.com/assets/6361812/18610456/a8314b90-7cd1-11e6-945a-21159ab9b3de.png)

**Comment by lheagy** [comment]
tests can be run locally using the command line from the `em_examples` folder by running

```
nosetests tests
```

**Comment by sgkang** [comment]
temporarily commented out this note book
