### ISSUE TITLE
DipoleWidget_ED.ipynb failing 

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em_examples#18]
The notebook: em_examples/notebooks/maxwell1_fundamentals/DipoleWidget_ED.ipynb is currently failing. Please see the [travis log](https://travis-ci.org/ubcgif/em_examples/builds/160711023) starting at line 499 
![image](https://cloud.githubusercontent.com/assets/6361812/18610479/55c62848-7cd2-11e6-94b0-1f5320bf79eb.png)

**Comment by sgkang** [comment]
Fixed.
