### ISSUE TITLE
Viz_Dipoles.ipynb corrupted 

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em_examples#19]
It looks like the file: 
em_examples/notebooks/maxwell1_fundamentals/Viz_Dipoles.ipynb
is corrupted (it is no longer json). Perhaps someone did a merge on the notebook?

(see lines 438 of the [travis log](https://travis-ci.org/ubcgif/em_examples)
![image](https://cloud.githubusercontent.com/assets/6361812/18610586/11c8f460-7cd5-11e6-9396-99865cc45e24.png)
)

I would suggest going back in the git history and finding a previous version of this notebook that works.

**Comment by sgkang** [comment]
Removed this notebook
