### ISSUE TITLE
DC Plate App

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em_examples#32]
Based on the 2D cylinder app, we need a plate app! The main impact here is examining the impact of shape on the charges and sensitivity 

![image](https://cloud.githubusercontent.com/assets/6361812/20950291/c20acb22-bbd3-11e6-9b90-975215cd57fb.png)

Parameters:
- inclination 
- sigma1
- sigma2
- dx
- dz 
- center
- A, B electrode locations

x is the reference

To view:
- currents
- charges
- potentials
- potential along a line at the surface (similar to the DC layered earth app) 

Also want to integrate the charges along the surface to get a total charge for each face of the plate

**Comment by lheagy** [comment]
What is the total positive charge built up. With the negative charge we now have a dipole. What is the distance between the charges and the magnitude of the dipole?  Each of these will make an electric dipole. What is the strength of the dipole.

**Comment by lheagy** [comment]
label charges 
![image](https://cloud.githubusercontent.com/assets/6361812/20950280/aeadd736-bbd3-11e6-83fc-ce31b942c05e.png)

**Comment by thast** [comment]
Repository link to DC lab (with 2D cylinder anomalie and 2-layer Earth with Fudge Factor):
https://github.com/ubcgif/gpgLabs/tree/master/DC

Associated Binder:
http://mybinder.org/repo/ubcgif/gpgLabs/notebooks/DC/DCLab.ipynb

**Comment by micmitch** [comment]
Working 2D and 2.5D versions of this app in em_examples.
