### ISSUE TITLE
DC Sensitivity function plots

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em_examples#33]
For each of 
- pole-dipole
- dipole-dipole
- pole-pole

plot the sensitivity function for a single datum in a 2D simulation of a half-space

**Comment by micmitch** [comment]
Added this functionality to the 2D plate app. With limited testing it seems to be working quite well.

**Comment by micmitch** [comment]
App will only run on the DCIP/dev branch at the moment due to the changes that I had to make in Rx.Pole class.

**Comment by lheagy** [comment]
kk, if it is a small change, would you mind starting a pr on simpeg of dcip/dev onto dev. We can get that merged in shortly

https://github.com/simpeg/simpeg/compare/dev...dcip/dev?expand=1. Thanks @micmitch!
