### ISSUE TITLE
DC example of a highly resistive layer 

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em_examples#34]
DC example showing a target beneath a highly resistive layer. Plot currents through the cross section and data. Show that we do not see the target

![image](https://cloud.githubusercontent.com/assets/6361812/20950723/431bf72a-bbd6-11e6-884d-60d37d1faa1d.png)

**Comment by micmitch** [comment]
Working 2D and 2.5D versions of this app in em_examples.
