### ISSUE TITLE
Simulations: FDEM; VMD; 1D earth

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em_examples#36]
Using the SimPEG cyl code, simulate a VMD over a layered earth

Parameters
- height of the loop (above, on or in earth) 
- freq
- 3 layers
   - h1
   - h2
   - log(sigma_1)
   - log(sigma_2) 
   - log(sigma_3)

Plot
- currents
- fields
- line of data (vertical or horizontal)

**Comment by sgkang** [comment]
Done
