### ISSUE TITLE
Todos: Cylinder app 

### ISSUE THREAD

**Issue by sgkang** [ubcgif/em_examples#40]
- [ ] add surface potential profile (use faked app res. calculation as we did in pseudo-section app)
![temp](https://cloud.githubusercontent.com/assets/6054371/21290398/de61ccce-c46d-11e6-87d3-704463e88a71.png)

- [ ] add center location of the cylinder
<img width="477" alt="temp" src="https://cloud.githubusercontent.com/assets/6054371/21290437/1ace1964-c46f-11e6-98f9-f818af364553.png">

- [ ] fix color bar issue

**Comment by lheagy** [comment]
![image](https://cloud.githubusercontent.com/assets/6361812/21290605/c95d4bf2-c475-11e6-9a40-760f254fd50d.png)

as well, in the plot of the potentials, please add a line that shows the half-space potential

**Comment by thast** [comment]
![screenshot 2016-12-20 11 46 31](https://cloud.githubusercontent.com/assets/13682747/21365383/02b6c91a-c6aa-11e6-883f-9a706443be53.png)

@sgkang , @lheagy , close the issues if you're happy!

**Comment by thast** [comment]
#44
