### ISSUE TITLE
sphereElectrostatic_example

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em_examples#6]
the code to run the electrostatic sphere example (https://github.com/simpeg/simpeg/blob/a9c9ce6bc8658317f3ad3e763b44cdc9db884f29/SimPEG/Examples/sphereElectrostatic_example.py) should be included in util_codes and the associated notebook updated to import the necessary code from there. 

This replaces the issue ubcgif/em#159

**Comment by thast** [comment]
See PR: #7
