### ISSUE TITLE
InteractiveDipoleDecay - Waveform 

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em_examples#67]
I see the keyword "Waveform" in this function, but it does not appear to do anything? @sgkang, can you confirm? If it does not do anything, we should remove the toggle buttons to remove confusion. 
 
![image](https://cloud.githubusercontent.com/assets/6361812/22858854/2495ac88-f07e-11e6-80c9-4e004e63e298.png)

**Comment by sgkang** [comment]
True.. this was a place holder. I'll deprecate at this point.

Seogi.



2017-02-12 9:20 GMT+08:00 Lindsey Heagy <notifications@github.com>:

**Comment by lheagy** [comment]
closed with #68
