### ISSUE TITLE
app check prior to next DISC

### ISSUE THREAD

**Issue by lheagy** [ubcgif/em_examples#84]
@dougoldenburg and @sgkang leave this weekend to present the DISC in Taiwan, Korea and Japan! To make sure things are running smoothly with the updated code, we need authors to open up their apps on [azure notebooks](https://notebooks.azure.com/library/em_apps) and make sure that 

(a) The notebook is up to date - ping me on slack if not
(b) The app runs without errors
(c) interactions with the apps work as expected (no duplicating plots etc). 

Once you have checked an app, please edit this issue by putting a tick in the box below to give it your green-light
- [x] DC_Building_Pseudosections.ipynb
- [x] DC_Cylinder_2D.ipynb
- [x] DC_Inversions.ipynb
- [x] DC_Layer_Cylinder_2D.ipynb
- [x] DC_Layer_Cylinder_2_5D.ipynb
- [x] DC_LayeredEarth.ipynb
- [x] DC_Overburden_2_5D.ipynb
- [x] DC_Plate2_5D.ipynb
- [x] DC_Plate_2D.ipynb
- [x] DC_Sphere_Constant_E.ipynb
- [x] FDEM_ElectricDipole_Wholespace.ipynb
- [x] FDEM_Inductive_Sphere.ipynb
- [x] FDEM_MagneticDipole_Wholespace.ipynb
- [x] FDEM_Planewave_Reflection.ipynb
- [x] FDEM_Planewave_Wholespace.ipynb
- [x] FDEM_VMD_LayeredEarth.ipynb
- [x] InductionRLcircuit_Harmonic.ipynb
- [x] InductionRLcircuit_Transient.ipynb
- [x] MarineCSEM_LayeredEarth.ipynb
- [x] MT_LayeredEarth.ipynb
- [x] PhyProp_ColeCole.ipynb
- [x] TDEM_ElectricDipole_Wholespace.ipynb
- [x] TDEM_HorizontalLoop_LayeredEarth.ipynb
- [x] TDEM_MagneticDipole_Wholespace.ipynb
- [x] TDEM_Planewave_Wholespace.ipynb

cc @thast, @dccowan, @sgkang, @micmitch

**Comment by micmitch** [comment]
Made a few minor corrections to several of the DC apps and pushed the changes to the patch_apps branches of em_examples and em_apps. 2.5D DC apps were not updated on Azure but I think that once they are the duplicate interact slider panels should disappear.

**Comment by dccowan** [comment]
Hi,

Here is the test results for my apps:

InductionRLcircuit_harmonic (works but updates plots a little slow)
InductionRLcircuit_transient (works and updates reasonably quickly)
FDEM_Inductive_Sphere (not uploaded to Azure)

Devin

**Comment by thast** [comment]
Up to date on Master but not on Azure (display button cause duplication of the widgets):
- DC_Layer_Cylinder_2_5D
- DC_Plate2_5D

**Comment by lheagy** [comment]
Thanks for your efforts everyone! I have updated azure to the most recent changes you all have made and uploaded the altered notebooks.
