### ISSUE TITLE
CVXopt package: slow to install on Azure, failed to run on Windows Machine

### ISSUE THREAD

**Issue by thast** [ubcgif/em_examples#97]
@dccowan : Do we still need the CVXopt package?
Here are a few things we notice during DISC Vancouver:
- Slow to pip install on Azure (up to several minutes!)
- We tried to install the em_examples on Nick's window machine, but the bdist_wheel install of cvxopt failed, thus preventing Nick to use it locally

**Comment by lheagy** [comment]
closed on #98
